name: avinyaapp
description: ReadyCoders
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  swipe: any
  outlined_text: any
  intl: any
  toggle_switch: ^2.1.0
  firebase_core: any
  cloud_firestore: any
  dotted_border: any
  google_fonts: any
  url_launcher: any
  file_picker: any
  firebase_storage: any
  firebase_auth: any
  flutter_spinkit: ^5.2.0
  marquee: any
  flutter_pdfview: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/